version: '3.7'
services:
  gmw_db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gitmostwanted
      - MYSQL_USER=gitmostwanted
      - MYSQL_PASSWORD=gitmostwanted_pwd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: unless-stopped

  gmw_redis:
    image: redis:latest
    restart: unless-stopped

  gmw_web:
    build: .
    user: gitmostwanted
    entrypoint: ["/opt/gitmostwanted/entrypoint.sh", "web"]
    restart: unless-stopped
    volumes:
      - .:/opt/gitmostwanted
    environment:
      - GMW_APP_SETTINGS=/opt/gitmostwanted/instance.cfg
      - GMW_GITHUB_SHA=${GMW_GITHUB_SHA}
    depends_on:
      - gmw_db
      - gmw_redis
# uncomment the following lines if you want to bind it to localhost (http://localhost:5000).
#    ports:
#      - "5000:5000"

  gmw_celery:
    build: .
    user: gitmostwanted
    restart: unless-stopped
    entrypoint: ["/opt/gitmostwanted/entrypoint.sh", "celery"]
    environment:
      - GMW_APP_SETTINGS=/opt/gitmostwanted/instance.cfg
    volumes:
      - .:/opt/gitmostwanted
    links:
      - gmw_db
      - gmw_redis
