# this file is used during the deployment process

version: '3.7'
services:
  gmw_db:
    volumes:
      - /home/github_gitmostwanted/data/mysql:/var/lib/mysql
    networks:
      - gmw_network

  gmw_redis:
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /home/github_gitmostwanted/data/redis:/data
    networks:
      - gmw_network

  gmw_celery:
    volumes:
      - /home/github_gitmostwanted/data/celery:/data
      - /home/github_gitmostwanted/gitmostwanted:/etc/gitmostwanted
    environment:
      - GMW_APP_ENV=production
      - GMW_APP_SETTINGS=/etc/gitmostwanted/instance.cfg
    networks:
      - gmw_network

  gmw_web:
    volumes:
      - /home/github_gitmostwanted/gitmostwanted:/etc/gitmostwanted
    environment:
      - GMW_APP_ENV=production
      - GMW_APP_SETTINGS=/etc/gitmostwanted/instance.cfg
      - GMW_GITHUB_SHA=${GMW_GITHUB_SHA}
    networks:
      - gmw_network

networks:
  gmw_network:
    external:
      name: traefik_default
